#!/bin/bash
keyname=$1
shift
if [ "$keyname" == "" ]
then
        echo "usage: sshotppass <keyname> ssh <username>@<host>"
        exit 0
fi
if [ "$(yq e ".$keyname.password" ~/.sshotp)" != "null" ]
then
	pwd="-p "$(yq e ".$keyname.password" ~/.sshotp | sed "s/ /\\ /g")
fi
if [ "$(yq e ".$keyname.otp" ~/.sshotp)" != "null" ]
then
	otp="-c oathtool\ --totp\ -b\ $(yq e ".$keyname.otp" ~/.sshotp | sed "s/ /\\ /g")"
fi
if [ "$(yq e ".$keyname.pwdcmp" ~/.sshotp)" != "null" ]
then
	pwdcmp="-P $(yq e ".$keyname.pwdcmp" ~/.sshotp | sed "s/ /\\ /g")"
fi
if [ "$(yq e ".$keyname.otpcmp" ~/.sshotp)" != "null" ]
then
	otpcmp="-O $(yq e ".$keyname.otpcmp" ~/.sshotp | sed "s/ /\\ /g")"
fi
sshpass $pwd $otp $pwdcmp $otpcmp $@

